name: C/C++ CI

on:
  push:
    branches: [ "REL_16_STABLE" ]
  pull_request:
    branches: [ "REL_16_STABLE" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    env:
      CFLAGS: "-std=c11"

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        mkdir _build
        export BUILD_PATH="$(realpath _build)"
        ./configure --prefix=$BUILD_PATH 
    - name: make
      run: |
        make -C src/port install
        make -C src/include install
        make -C src/common install
        make -C src/interfaces/libpq install
        rm -rf _build/lib/*.so
        rm -rf _build/lib/*.so.*
        tar -czf libpq-fe.tar.gz _build
        rm -rf _build
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        path: libpq-fe.tar.gz
          
          
        
        
    
