name: C/C++ CI

on:
  push:
    branches: [ "REL_16_STABLE" ]
  pull_request:
    branches: [ "REL_16_STABLE" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CFLAGS: "-std=c11"

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        mkdir _build
        export BUILD_PATH="$(realpath _build)"
        ./configure --prefix=BUILD_PATH 
    - name: make
      run: make -C src/interfaces/libpq install
