name: C/C++ CI

on:
  push:
    branches: [ "REL_16_STABLE" ]
  pull_request:
    branches: [ "REL_16_STABLE" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CFLAGS: "-std=c11 -static"

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make -C src/interfaces/libpq install
